#!/bin/sh

NAME=HealpixCxx-3.0pre
URL=https://healpix.svn.sourceforge.net/svnroot/healpix/trunk/src/cxx
REV=HEAD

svn export -r ${REV} ${URL} ${NAME} &&\
cd ${NAME} &&\
mv autotools/Makefile.am autotools/configure.ac . &&\
autoreconf --install &&\
make distcheck
