#!/bin/sh
# replace SECTION000xxx00000000000000 with SECTIONxxx
#
# Changes:
#   28-Feb-2017: EH

# Get the directory path or filename
if [ -z "$1" ]; then
  cat <<EOF
Shorten SECTION tag generated by latex2html
Usage: $0 <directory_with_problematic_HTML_files OR file_name_radix>
EOF
  exit
fi



# Fix each HTML file
tmpfile='/tmp/html_edit.txt'
for d in $* ; do
echo "--------- $d ---------"
for file in `ls -1 ${d}*.htm` ; do
found=`grep SECTION000 ${file} | wc -l`
if [ ${found} != 0 ] ; then
    # echo "editing HTML ${file}"
    cat ${file} | sed  "s/SECTION000\([0-9]*\)00000000000000\"/SECTION\1\"/g" > ${tmpfile}
    mv ${tmpfile} ${file}
else
    echo "       SKIP    ($0)          ${file}"
fi
done
done


exit

