#!/bin/sh

NAME=HealpixJava-3.12pre
URL=https://healpix.svn.sourceforge.net/svnroot/healpix/trunk/src/java
REV=HEAD

svn export -r ${REV} ${URL} ${NAME} &&\
cd ${NAME} &&\
rm -rf make_release README &&\
cd .. &&\
tar cvzf ${NAME}-src.tar.gz ${NAME} &&\
cd ${NAME} &&\
export CLASSPATH=${CLASSPATH}:`pwd`/lib/junit-4.11.jar &&\
ant &&\
cd .. &&\
cp ${NAME}/dist/jhealpix.jar ./${NAME}-bin.jar &&\
mv ${NAME}/doc ./${NAME}-doc &&\
tar cvzf ${NAME}-doc.tar.gz ${NAME}-doc &&\
rm -rf ${NAME}-doc &&\
rm -rf ${NAME}
