#!/bin/sh

NAME=CHealpix-3.0pre
URL=https://healpix.svn.sourceforge.net/svnroot/healpix/trunk/src/C
REV=HEAD

svn export -r ${REV} ${URL} ${NAME} &&\
rm -f ${NAME}/make_release &&\
tar cvzf ${NAME}-src.tar.gz ${NAME} &&\
rm -rf ${NAME}
